//! 命令行集成：安装后在用户 PATH 中注册 `dsh` 命令。
//!
//! `dsh` 是 Node 脚本（`@deepseek-ai/dsh/lib/bin.js`），并非原生可执行文件，
//! 因此这里生成包装脚本（shim）并注册到用户 PATH：
//!
//! - Windows：`%LOCALAPPDATA%\deepseek-harness\bin\dsh.cmd` + `dsh.ps1`，
//!   通过 `HKCU\Environment\Path` 注册并广播 `WM_SETTINGCHANGE`；
//! - macOS/Linux：`~/.local/bin/dsh`，必要时向 `~/.zshrc` / `~/.bashrc`
//!   幂等追加 PATH 导出（带标记块，可干净移除）。
//!
//! shim 运行时优先使用本地版本兼容的 node（校验规则与
//! [`crate::config::is_supported_node_version`] 一致），否则回退到捆绑运行时。
//! shim 不重定向 stdin/stdout、不修改工作目录，保证交互式 `dsh` 可用，
//! 并透传全部参数与退出码。

use crate::config;
use serde::Serialize;
use std::fs;
use std::path::{Path, PathBuf};
use tauri::{AppHandle, Manager};

/// Windows 下 shim 根目录名（`%LOCALAPPDATA%\<此目录>\bin`）
const CLI_ROOT_DIR_NAME: &str = "deepseek-harness";
/// Windows 下 shim 文件名（cmd 为主入口，ps1 供 PowerShell 原生体验）
const SHIM_CMD_NAME: &str = "dsh.cmd";
const SHIM_PS1_NAME: &str = "dsh.ps1";
/// Unix 下 shim 文件名
#[cfg_attr(windows, allow(dead_code))]
const SHIM_SH_NAME: &str = "dsh";
/// Unix 下 shim 所在目录（XDG 约定）
#[cfg_attr(windows, allow(dead_code))]
const UNIX_BIN_DIR: &str = ".local/bin";

/// shell rc 注入标记（用于幂等增删）
#[cfg_attr(windows, allow(dead_code))]
const RC_MARK_START: &str = "# >>> deepseek-harness dsh >>>";
#[cfg_attr(windows, allow(dead_code))]
const RC_MARK_END: &str = "# <<< deepseek-harness dsh <<<";

/// Unix 下需要写入 PATH 导出的 rc 文件（按顺序处理）
#[cfg_attr(windows, allow(dead_code))]
const RC_FILES: [&str; 2] = [".zshrc", ".bashrc"];

/// 命令行集成状态（设置页展示）
#[derive(Debug, Clone, Serialize)]
pub struct CliLinkStatus {
    /// 用户开关（Setting.cli_link_enabled）
    pub enabled: bool,
    /// 主 shim 文件是否存在
    pub shim_exists: bool,
    /// bin 目录是否已在用户 PATH 中注册
    pub path_registered: bool,
    /// bin 目录绝对路径
    pub bin_dir: String,
    /// 主 shim 文件绝对路径
    pub shim_path: String,
}

// ---------------------------------------------------------------------------
// 路径计算
// ---------------------------------------------------------------------------

/// bin 目录：
/// - Windows：`%LOCALAPPDATA%\deepseek-harness\bin`（用户级、不随应用数据目录变动）
/// - Unix：`~/.local/bin`（XDG 约定，通常已在 PATH 中）
fn get_bin_dir(app_handle: &AppHandle) -> PathBuf {
    #[cfg(windows)]
    {
        let local = std::env::var_os("LOCALAPPDATA")
            .map(PathBuf::from)
            .or_else(|| {
                app_handle
                    .path()
                    .local_data_dir()
                    .ok()
                    .and_then(|d| d.parent().map(|p| p.to_path_buf()))
            })
            .unwrap_or_else(std::env::temp_dir);
        local.join(CLI_ROOT_DIR_NAME).join("bin")
    }
    #[cfg(not(windows))]
    {
        let home = app_handle
            .path()
            .home_dir()
            .unwrap_or_else(|| PathBuf::from("."));
        home.join(UNIX_BIN_DIR)
    }
}

/// 主 shim 文件路径
fn get_shim_path(app_handle: &AppHandle) -> PathBuf {
    #[cfg(windows)]
    {
        get_bin_dir(app_handle).join(SHIM_CMD_NAME)
    }
    #[cfg(not(windows))]
    {
        get_bin_dir(app_handle).join(SHIM_SH_NAME)
    }
}

/// 当前用户 PATH 中是否已包含 bin 目录（Windows 以注册表为准，
/// 因为进程内 PATH 在广播 WM_SETTINGCHANGE 后不会自动更新）
fn path_registered(app_handle: &AppHandle) -> bool {
    #[cfg(windows)]
    {
        let bin_dir = get_bin_dir(app_handle);
        let Some(bin_str) = bin_dir.to_str() else {
            return false;
        };
        read_user_path()
            .map(|value| path_contains_token(&value, bin_str))
            .unwrap_or(false)
    }
    #[cfg(not(windows))]
    {
        let bin_dir = get_bin_dir(app_handle);
        // 1. 当前进程 PATH 已包含（新终端直接可用）
        if std::env::split_paths(&std::env::var_os("PATH").unwrap_or_default())
            .any(|p| p == bin_dir)
        {
            return true;
        }
        // 2. rc 文件中已注入标记块（重启 shell 后可用）
        let home = app_handle
            .path()
            .home_dir()
            .unwrap_or_else(|| PathBuf::from("."));
        RC_FILES.iter().any(|name| {
            fs::read_to_string(home.join(name))
                .map(|content| content.contains(RC_MARK_START))
                .unwrap_or(false)
        })
    }
}

// ---------------------------------------------------------------------------
// shim 内容生成（纯函数，便于测试）
// ---------------------------------------------------------------------------

/// Windows `dsh.cmd` 内容。`app_dir` 为应用数据目录（绝对路径，生成时写死）。
// 生产环境仅在 Windows 使用；Unix 构建下仍编译（供跨平台测试引用）。
#[cfg_attr(all(not(windows), not(test)), allow(dead_code))]
fn build_cmd_shim(app_dir: &Path) -> String {
    let dsh_bin = app_dir
        .join("dependencies/dsh/node_modules/@deepseek-ai/dsh/lib/bin.js");
    let dsh_home = app_dir.join("data/dsh");
    // 批处理中 `%` 会被展开，需写成 `%%`
    let esc = |s: &Path| s.to_string_lossy().replace('%', "%%");
    format!(
        r#"@echo off
rem DeepSeek Harness Desktop - dsh command shim (generated)
rem Do not edit: regenerated by the desktop app on install/startup.
setlocal
set "DSH_APP_DIR={app_dir}"
set "DSH_BIN={dsh_bin}"
set "DSH_HOME={dsh_home}"
set "DSH_TELEMETRY_DISABLED=1"

rem Prefer a version-compatible local node, fall back to the bundled runtime.
where node >nul 2>nul
if errorlevel 1 goto :use_bundled
for /f "delims=" %%v in ('node --version 2^>nul') do set "NODE_V=%%v"
powershell -NoProfile -ExecutionPolicy Bypass -Command "& {{ param($v) if ($v -match '^v(\d+)\.(\d+)') {{ $m=[int]$matches[1]; $n=[int]$matches[2]; if (($m -eq 22 -and $n -ge 15) -or ($m -eq 23 -and $n -ge 8) -or $m -ge 24) {{ exit 0 }} }}; exit 1 }}" "%NODE_V%" >nul 2>nul
if errorlevel 1 goto :use_bundled
set "NODE=node"
goto :launch

:use_bundled
if not exist "%DSH_APP_DIR%\runtime\node.exe" goto :no_node
set "NODE=%DSH_APP_DIR%\runtime\node.exe"
set "PATH=%DSH_APP_DIR%\runtime;%PATH%"

:launch
if not exist "%DSH_BIN%" goto :no_cli
"%NODE%" "%DSH_BIN%" %*
exit /b %ERRORLEVEL%

:no_cli
echo [dsh] Harness CLI not found. Please run DeepSeek Harness Desktop to install it first. 1>&2
exit /b 1

:no_node
echo [dsh] Node.js runtime not found. Please run DeepSeek Harness Desktop to install it first. 1>&2
exit /b 1
"#,
        app_dir = esc(app_dir),
        dsh_bin = esc(&dsh_bin),
        dsh_home = esc(&dsh_home),
    )
}

/// Windows `dsh.ps1` 内容
#[cfg_attr(all(not(windows), not(test)), allow(dead_code))]
fn build_ps1_shim(app_dir: &Path) -> String {
    let dsh_bin = app_dir.join("dependencies/dsh/node_modules/@deepseek-ai/dsh/lib/bin.js");
    let dsh_home = app_dir.join("data/dsh");
    // 单引号字符串中 `'` 需翻倍
    let esc = |s: &Path| s.to_string_lossy().replace('\'', "''");
    format!(
        r#"# DeepSeek Harness Desktop - dsh command shim (generated)
# Do not edit: regenerated by the desktop app on install/startup.
$ErrorActionPreference = "Stop"
$appDir = '{app_dir}'
$dshBin = '{dsh_bin}'
$env:DSH_HOME = '{dsh_home}'
$env:DSH_TELEMETRY_DISABLED = '1'

# Prefer a version-compatible local node, fall back to the bundled runtime.
$node = $null
$localNode = Get-Command node -ErrorAction SilentlyContinue
if ($localNode) {{
    try {{
        $version = & node --version 2>$null
        if ($version -match '^v(\d+)\.(\d+)') {{
            $major = [int]$matches[1]
            $minor = [int]$matches[2]
            if (($major -eq 22 -and $minor -ge 15) -or ($major -eq 23 -and $minor -ge 8) -or $major -ge 24) {{
                $node = 'node'
            }}
        }}
    }} catch {{ }}
}}
if (-not $node) {{
    $bundled = Join-Path $appDir 'runtime\node.exe'
    if (Test-Path -LiteralPath $bundled) {{
        $node = $bundled
        $env:PATH = (Split-Path -Parent $bundled) + ';' + $env:PATH
    }}
}}
if (-not $node) {{
    Write-Error '[dsh] Node.js runtime not found. Please run DeepSeek Harness Desktop to install it first.'
    exit 1
}}
if (-not (Test-Path -LiteralPath $dshBin)) {{
    Write-Error '[dsh] Harness CLI not found. Please run DeepSeek Harness Desktop to install it first.'
    exit 1
}}
& $node $dshBin @args
exit $LASTEXITCODE
"#,
        app_dir = esc(app_dir),
        dsh_bin = esc(&dsh_bin),
        dsh_home = esc(&dsh_home),
    )
}

/// Unix `dsh` shell 脚本内容（POSIX sh）
#[cfg_attr(all(windows, not(test)), allow(dead_code))]
fn build_sh_shim(app_dir: &Path) -> String {
    let dsh_bin = app_dir.join("dependencies/dsh/node_modules/@deepseek-ai/dsh/lib/bin.js");
    let dsh_home = app_dir.join("data/dsh");
    // 单引号字符串中 `'` 需写成 `'\''`
    let esc = |s: &Path| s.to_string_lossy().replace('\'', "'\\''");
    format!(
        r#"#!/bin/sh
# DeepSeek Harness Desktop - dsh command shim (generated)
# Do not edit: regenerated by the desktop app on install/startup.
APP_DIR='{app_dir}'
DSH_BIN='{dsh_bin}'
export DSH_HOME='{dsh_home}'
export DSH_TELEMETRY_DISABLED=1

# Prefer a version-compatible local node, fall back to the bundled runtime.
NODE=""
if command -v node >/dev/null 2>&1; then
  NODE_V=$(node --version 2>/dev/null)
  MAJOR=$(printf '%s' "$NODE_V" | awk -F. '{{ gsub(/^v/, "", $1); print $1 }}')
  MINOR=$(printf '%s' "$NODE_V" | awk -F. '{{ print $2 }}')
  if {{ [ -n "$MAJOR" ] && [ "$MAJOR" -ge 24 ]; }} 2>/dev/null || \
     {{ [ "$MAJOR" -eq 22 ] && [ "$MINOR" -ge 15 ]; }} 2>/dev/null || \
     {{ [ "$MAJOR" -eq 23 ] && [ "$MINOR" -ge 8 ]; }} 2>/dev/null; then
    NODE="node"
  fi
fi
if [ -z "$NODE" ]; then
  if [ -x "$APP_DIR/runtime/bin/node" ]; then
    NODE="$APP_DIR/runtime/bin/node"
    export PATH="$APP_DIR/runtime/bin:$PATH"
  fi
fi
if [ -z "$NODE" ]; then
  echo "[dsh] Node.js runtime not found. Please run DeepSeek Harness Desktop to install it first." >&2
  exit 1
fi
if [ ! -f "$DSH_BIN" ]; then
  echo "[dsh] Harness CLI not found. Please run DeepSeek Harness Desktop to install it first." >&2
  exit 1
fi
exec "$NODE" "$DSH_BIN" "$@"
"#,
        app_dir = esc(app_dir),
        dsh_bin = esc(&dsh_bin),
        dsh_home = esc(&dsh_home),
    )
}

/// 将 shim 文件写入 bin 目录（覆盖式，保证自愈后内容与当前安装一致）
fn write_shims(app_handle: &AppHandle, bin_dir: &Path) -> Result<(), String> {
    let app_dir = config::get_base_dir(app_handle);
    fs::create_dir_all(bin_dir).map_err(|e| format!("create bin dir failed: {e}"))?;

    #[cfg(windows)]
    {
        fs::write(bin_dir.join(SHIM_CMD_NAME), build_cmd_shim(&app_dir))
            .map_err(|e| format!("write {} failed: {e}", SHIM_CMD_NAME))?;
        fs::write(bin_dir.join(SHIM_PS1_NAME), build_ps1_shim(&app_dir))
            .map_err(|e| format!("write {} failed: {e}", SHIM_PS1_NAME))?;
    }
    #[cfg(not(windows))]
    {
        let shim = bin_dir.join(SHIM_SH_NAME);
        fs::write(&shim, build_sh_shim(&app_dir))
            .map_err(|e| format!("write {} failed: {e}", SHIM_SH_NAME))?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&shim, fs::Permissions::from_mode(0o755))
                .map_err(|e| format!("chmod shim failed: {e}"))?;
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// PATH 注册（Windows：注册表 + WM_SETTINGCHANGE；Unix：shell rc）
// ---------------------------------------------------------------------------

/// 注册 bin 目录到用户 PATH（幂等）
fn register_path(app_handle: &AppHandle) -> Result<(), String> {
    if path_registered(app_handle) {
        return Ok(());
    }
    #[cfg(windows)]
    {
        let bin_dir = get_bin_dir(app_handle);
        let bin_str = bin_dir
            .to_str()
            .ok_or_else(|| "bin dir is not valid UTF-8".to_string())?;
        let current = read_user_path().unwrap_or_default();
        let new_value = if current.trim().is_empty() {
            bin_str.to_string()
        } else {
            format!("{};{}", current.trim_end_matches(';'), bin_str)
        };
        write_user_path(&new_value)?;
        notify_environment_change();
        log::info!("Registered dsh bin dir in user PATH: {bin_str}");
    }
    #[cfg(not(windows))]
    {
        inject_shell_rc(app_handle)?;
    }
    Ok(())
}

/// 从用户 PATH 中移除 bin 目录（幂等）
fn unregister_path(app_handle: &AppHandle) -> Result<(), String> {
    #[cfg(windows)]
    {
        let bin_dir = get_bin_dir(app_handle);
        let Some(bin_str) = bin_dir.to_str() else {
            return Ok(());
        };
        if let Some(current) = read_user_path() {
            if !path_contains_token(&current, bin_str) {
                return Ok(());
            }
            let new_value = remove_path_token(&current, bin_str);
            write_user_path(&new_value)?;
            notify_environment_change();
            log::info!("Removed dsh bin dir from user PATH");
        }
    }
    #[cfg(not(windows))]
    {
        strip_shell_rc(app_handle)?;
    }
    Ok(())
}

#[cfg(windows)]
fn read_user_path() -> Option<String> {
    use windows_sys::Win32::Foundation::{ERROR_FILE_NOT_FOUND, ERROR_MORE_DATA};
    use windows_sys::Win32::System::Registry::{
        RegCloseKey, RegOpenKeyExW, RegQueryValueExW, HKEY, HKEY_CURRENT_USER, KEY_QUERY_VALUE,
    };

    let to_wide = |s: &str| -> Vec<u16> {
        s.encode_utf16().chain(std::iter::once(0)).collect()
    };

    unsafe {
        let mut hkey: HKEY = std::ptr::null_mut();
        let key_name = to_wide("Environment");
        let ret = RegOpenKeyExW(
            HKEY_CURRENT_USER,
            key_name.as_ptr(),
            0,
            KEY_QUERY_VALUE,
            &mut hkey,
        );
        if ret != 0 {
            log::warn!("failed to open HKCU\\Environment (error {ret})");
            return None;
        }

        let value_name = to_wide("Path");
        let mut value_type: u32 = 0;
        let mut size: u32 = 0;
        let mut ret = RegQueryValueExW(
            hkey,
            value_name.as_ptr(),
            std::ptr::null(),
            &mut value_type,
            std::ptr::null_mut(),
            &mut size,
        );
        if ret == ERROR_FILE_NOT_FOUND {
            RegCloseKey(hkey);
            return Some(String::new());
        }
        if ret != ERROR_MORE_DATA && ret != 0 {
            RegCloseKey(hkey);
            log::warn!("failed to query HKCU\\Environment\\Path (error {ret})");
            return None;
        }

        let mut buf = vec![0u16; (size as usize / 2).max(1) + 1];
        ret = RegQueryValueExW(
            hkey,
            value_name.as_ptr(),
            std::ptr::null(),
            &mut value_type,
            buf.as_mut_ptr() as *mut u8,
            &mut size,
        );
        RegCloseKey(hkey);
        if ret != 0 {
            log::warn!("failed to read HKCU\\Environment\\Path (error {ret})");
            return None;
        }
        let end = buf.iter().position(|&c| c == 0).unwrap_or(buf.len());
        Some(String::from_utf16_lossy(&buf[..end]))
    }
}

#[cfg(windows)]
fn write_user_path(new_value: &str) -> Result<(), String> {
    use windows_sys::Win32::System::Registry::{
        RegCloseKey, RegOpenKeyExW, RegQueryValueExW, RegSetValueExW, HKEY, HKEY_CURRENT_USER,
        KEY_QUERY_VALUE, KEY_SET_VALUE, REG_EXPAND_SZ, REG_SZ,
    };

    let to_wide = |s: &str| -> Vec<u16> {
        s.encode_utf16().chain(std::iter::once(0)).collect()
    };

    unsafe {
        let mut hkey: HKEY = std::ptr::null_mut();
        let key_name = to_wide("Environment");
        let ret = RegOpenKeyExW(
            HKEY_CURRENT_USER,
            key_name.as_ptr(),
            0,
            KEY_QUERY_VALUE | KEY_SET_VALUE,
            &mut hkey,
        );
        if ret != 0 {
            return Err(format!("failed to open HKCU\\Environment (error {ret})"));
        }

        // 保留原值类型（REG_EXPAND_SZ / REG_SZ）
        let value_name = to_wide("Path");
        let mut value_type: u32 = REG_EXPAND_SZ;
        let mut size: u32 = 0;
        RegQueryValueExW(
            hkey,
            value_name.as_ptr(),
            std::ptr::null(),
            &mut value_type,
            std::ptr::null_mut(),
            &mut size,
        );
        if value_type != REG_SZ && value_type != REG_EXPAND_SZ {
            value_type = REG_EXPAND_SZ;
        }

        let wide_value = to_wide(new_value);
        let bytes = (wide_value.len() * 2) as u32;
        let ret = RegSetValueExW(
            hkey,
            value_name.as_ptr(),
            0,
            value_type,
            wide_value.as_ptr() as *const u8,
            bytes,
        );
        RegCloseKey(hkey);
        if ret != 0 {
            return Err(format!("failed to write HKCU\\Environment\\Path (error {ret})"));
        }
        Ok(())
    }
}

#[cfg(windows)]
fn notify_environment_change() {
    use windows_sys::Win32::Foundation::{LPARAM, WPARAM};
    use windows_sys::Win32::UI::WindowsAndMessaging::{
        SendMessageTimeoutW, HWND_BROADCAST, SMTO_ABORTIFHUNG, WM_SETTINGCHANGE,
    };
    let wide: Vec<u16> = "Environment".encode_utf16().chain(Some(0)).collect();
    unsafe {
        SendMessageTimeoutW(
            HWND_BROADCAST,
            WM_SETTINGCHANGE,
            0 as WPARAM,
            wide.as_ptr() as LPARAM,
            SMTO_ABORTIFHUNG,
            5000,
            std::ptr::null_mut(),
        );
    }
}

/// 展开字符串中的 `%VAR%`（Windows）
#[cfg(windows)]
fn expand_env(value: &str) -> String {
    use windows_sys::Win32::System::Environment::ExpandEnvironmentStringsW;
    let wide: Vec<u16> = value.encode_utf16().chain(Some(0)).collect();
    let mut buf = vec![0u16; 32768];
    let n = unsafe { ExpandEnvironmentStringsW(wide.as_ptr(), buf.as_mut_ptr(), buf.len() as u32) };
    if n == 0 || n > buf.len() as u32 {
        return value.to_string();
    }
    let end = buf.iter().position(|&c| c == 0).unwrap_or(buf.len());
    String::from_utf16_lossy(&buf[..end])
}

/// PATH 值（`;` 分隔）中是否已包含指定目录（大小写不敏感，先展开 %VAR%）
#[cfg(windows)]
fn path_contains_token(path_value: &str, token: &str) -> bool {
    let expanded = expand_env(path_value);
    let token_lower = token.to_lowercase();
    expanded
        .split(';')
        .any(|p| !p.is_empty() && p.trim_end_matches('\\').to_lowercase() == token_lower)
}

/// 从 PATH 值中移除指定目录 token（同时处理 `%LOCALAPPDATA%` 未展开形式）
#[cfg(windows)]
fn remove_path_token(path_value: &str, token: &str) -> String {
    let token_lower = token.to_lowercase();
    // `%LOCALAPPDATA%\deepseek-harness\bin` 的未展开形式
    let unexpanded_lower = token_lower
        .replace(
            &std::env::var("LOCALAPPDATA").unwrap_or_default().to_lowercase(),
            "%localappdata%",
        );
    let kept: Vec<&str> = path_value
        .split(';')
        .filter(|p| {
            if p.is_empty() {
                return false;
            }
            let norm = p.trim_end_matches('\\').to_lowercase();
            norm != token_lower && norm != unexpanded_lower
        })
        .collect();
    kept.join(";")
}

/// Unix：向 `~/.zshrc` / `~/.bashrc` 幂等注入 `~/.local/bin` 的 PATH 导出
#[cfg(not(windows))]
fn inject_shell_rc(app_handle: &AppHandle) -> Result<(), String> {
    use std::path::PathBuf as _;

    let home = app_handle
        .path()
        .home_dir()
        .ok_or_else(|| "failed to resolve home directory".to_string())?;
    let block = format!(
        "{start}\nexport PATH=\"$HOME/.local/bin:$PATH\"\n{end}\n",
        start = RC_MARK_START,
        end = RC_MARK_END
    );

    for name in RC_FILES {
        let rc_path = home.join(name);
        let mut content = fs::read_to_string(&rc_path).unwrap_or_default();
        if content.contains(RC_MARK_START) {
            continue;
        }
        if !content.is_empty() && !content.ends_with('\n') {
            content.push('\n');
        }
        content.push_str(&block);
        fs::write(&rc_path, content)
            .map_err(|e| format!("write {} failed: {e}", rc_path.display()))?;
        log::info!("Injected PATH export into {}", rc_path.display());
    }
    Ok(())
}

/// Unix：从 rc 文件中移除注入块
#[cfg(not(windows))]
fn strip_shell_rc(app_handle: &AppHandle) -> Result<(), String> {
    let home = app_handle
        .path()
        .home_dir()
        .ok_or_else(|| "failed to resolve home directory".to_string())?;
    for name in RC_FILES {
        let rc_path = home.join(name);
        let content = fs::read_to_string(&rc_path).unwrap_or_default();
        let cleaned = strip_rc_block(&content);
        if cleaned != content {
            fs::write(&rc_path, cleaned)
                .map_err(|e| format!("write {} failed: {e}", rc_path.display()))?;
            log::info!("Removed PATH export from {}", rc_path.display());
        }
    }
    Ok(())
}

/// 移除 rc 文件中的标记块（含标记行本身）
#[cfg_attr(all(windows, not(test)), allow(dead_code))]
fn strip_rc_block(content: &str) -> String {
    let mut lines = content.lines().peekable();
    let mut out = String::new();
    let mut skipping = false;
    while let Some(line) = lines.next() {
        if line.trim() == RC_MARK_START {
            skipping = true;
            continue;
        }
        if skipping {
            if line.trim() == RC_MARK_END {
                skipping = false;
            }
            continue;
        }
        out.push_str(line);
        out.push('\n');
    }
    out
}

// ---------------------------------------------------------------------------
// 对外接口
// ---------------------------------------------------------------------------

/// 当前命令行集成状态
pub fn get_status(app_handle: &AppHandle) -> CliLinkStatus {
    let setting = config::get_store_dat_setting(app_handle);
    let shim_path = get_shim_path(app_handle);
    CliLinkStatus {
        enabled: setting.cli_link_enabled,
        shim_exists: shim_path.is_file(),
        path_registered: path_registered(app_handle),
        bin_dir: get_bin_dir(app_handle).to_string_lossy().into_owned(),
        shim_path: shim_path.to_string_lossy().into_owned(),
    }
}

/// 启用并确保命令行集成完整（幂等，可随时重跑自愈）
///
/// 只做 shim 生成与 PATH 注册，不要求 node/dsh 已安装——运行时缺失时
/// shim 会给出友好报错，因此安装前后调用都是安全的。
pub fn ensure(app_handle: &AppHandle) -> Result<CliLinkStatus, String> {
    // 保证 DSH_HOME 目录存在（shim 会写入该路径）
    let dsh_home = config::get_dsh_data_path(app_handle);
    fs::create_dir_all(&dsh_home).map_err(|e| format!("create dsh home failed: {e}"))?;

    let bin_dir = get_bin_dir(app_handle);
    write_shims(app_handle, &bin_dir)?;
    register_path(app_handle)?;

    log::info!("dsh CLI link ensured at {}", bin_dir.display());
    Ok(get_status(app_handle))
}

/// 禁用并清理命令行集成（删除 shim + 移除 PATH 注册）
pub fn remove(app_handle: &AppHandle) -> Result<CliLinkStatus, String> {
    let bin_dir = get_bin_dir(app_handle);

    #[cfg(windows)]
    {
        let _ = fs::remove_file(bin_dir.join(SHIM_CMD_NAME));
        let _ = fs::remove_file(bin_dir.join(SHIM_PS1_NAME));
    }
    #[cfg(not(windows))]
    {
        let _ = fs::remove_file(bin_dir.join(SHIM_SH_NAME));
    }

    unregister_path(app_handle)?;

    log::info!("dsh CLI link removed");
    Ok(get_status(app_handle))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_app_dir() -> PathBuf {
        if cfg!(windows) {
            PathBuf::from(r"C:\Users\test\AppData\Roaming\io.github.hairyf.deepseek-harness-desktop")
        } else {
            PathBuf::from("/home/test/.local/share/io.github.hairyf.deepseek-harness-desktop")
        }
    }

    #[test]
    fn cmd_shim_contains_baked_paths() {
        let content = build_cmd_shim(&sample_app_dir());
        assert!(content.contains(r"C:\Users\test\AppData\Roaming"));
        assert!(content.contains("dependencies/dsh/node_modules/@deepseek-ai/dsh/lib/bin.js"));
        assert!(content.contains("data/dsh"));
        assert!(content.contains("%*"));
    }

    #[test]
    fn cmd_shim_escapes_percent() {
        let dir = PathBuf::from(r"C:\Users\100%test\AppData\Roaming\io.github.hairyf.deepseek-harness-desktop");
        let content = build_cmd_shim(&dir);
        assert!(content.contains("100%%test"));
        assert!(!content.contains(r#"set "DSH_APP_DIR=C:\Users\100%test""#));
    }

    #[test]
    fn ps1_shim_escapes_quotes() {
        let dir = PathBuf::from(r"C:\Users\o'brien\AppData\Roaming\io.github.hairyf.deepseek-harness-desktop");
        let content = build_ps1_shim(&dir);
        assert!(content.contains("o''brien"));
        assert!(content.contains("@args"));
    }

    #[test]
    fn sh_shim_has_shebang_and_exec() {
        let content = build_sh_shim(&sample_app_dir());
        assert!(content.starts_with("#!/bin/sh"));
        assert!(content.contains(r#"exec "$NODE" "$DSH_BIN" "$@""#));
        // 捆绑运行时回退路径
        assert!(content.contains(r#"$APP_DIR/runtime/bin/node"#));
    }

    #[test]
    fn sh_shim_escapes_quotes() {
        let dir = PathBuf::from("/home/o'brien/.local/share/io.github.hairyf.deepseek-harness-desktop");
        let content = build_sh_shim(&dir);
        assert!(content.contains("o'\\''brien"));
    }

    #[test]
    fn rc_block_roundtrip() {
        let block = format!(
            "{start}\nexport PATH=\"$HOME/.local/bin:$PATH\"\n{end}\n",
            start = RC_MARK_START,
            end = RC_MARK_END
        );
        let mut content = "# existing\n".to_string();
        content.push_str(&block);
        content.push_str("echo hi\n");
        let cleaned = strip_rc_block(&content);
        assert_eq!(cleaned, "# existing\necho hi\n");
        assert!(!cleaned.contains(RC_MARK_START));
        assert!(!cleaned.contains(RC_MARK_END));
        // 幂等：已清理的内容再次清理保持不变
        assert_eq!(strip_rc_block(&cleaned), cleaned);
    }

    #[cfg(windows)]
    #[test]
    fn path_token_helpers() {
        let local = std::env::var("LOCALAPPDATA").expect("LOCALAPPDATA should be set");
        let token = format!(r"{}\deepseek-harness\bin", local);
        let value = format!(r"C:\Windows;{};C:\Other", token);
        assert!(path_contains_token(&value, &token));
        let removed = remove_path_token(&value, &token);
        assert!(!path_contains_token(&removed, &token));
        assert!(removed.contains(r"C:\Windows"));
        assert!(removed.contains(r"C:\Other"));
        assert!(!removed.contains("deepseek-harness"));
    }

    #[cfg(windows)]
    #[test]
    fn user_path_registry_roundtrip() {
        // 只读回写相同值：验证注册表读写与广播链路，不改变任何内容。
        // 受限环境（沙箱/CI 无注册表写权限）下跳过，不视为失败。
        let current = read_user_path().expect("HKCU\\Environment\\Path should be readable");
        if let Err(e) = write_user_path(&current) {
            if e.contains("error 5") {
                eprintln!("SKIP: registry write denied by environment: {e}");
                return;
            }
            panic!("write back same value should succeed: {e}");
        }
        notify_environment_change();
        let after = read_user_path().expect("HKCU\\Environment\\Path should be readable");
        assert_eq!(current, after);
    }
}
