//! shim 脚本内容生成：`dsh` / `pnpm` 的 cmd、ps1、sh 包装脚本与落盘。
//!
//! 各构建函数是纯函数（便于测试），`write_shims` 负责写入 bin 目录。
//! shim 文本必须全英文：cmd/ps1 按系统代码页解析，中文注释会乱码成命令执行。

use crate::config;
use std::fs;
use std::path::Path;
use tauri::AppHandle;

/// Windows 下 shim 文件名（cmd 为主入口，ps1 供 PowerShell 原生体验）
pub const SHIM_CMD_NAME: &str = "dsh.cmd";
pub const SHIM_PS1_NAME: &str = "dsh.ps1";
pub const PNPM_SHIM_CMD_NAME: &str = "pnpm.cmd";
pub const PNPM_SHIM_PS1_NAME: &str = "pnpm.ps1";

/// Unix 下 shim 文件名
#[cfg(unix)]
pub const SHIM_SH_NAME: &str = "dsh";
#[cfg(unix)]
pub const PNPM_SHIM_SH_NAME: &str = "pnpm";

// ---------------------------------------------------------------------------
// shim 共享片段：node 解析逻辑（dsh / pnpm shim 共用）
//
// 规则：优先 PATH 中版本兼容的本地 node（v22.15+ / v23.8+ / v24+，
// 与 config::is_supported_node_version 一致），否则回退捆绑运行时。
// 变量约定：cmd 用 %APP_DIR%，ps1 用 $appDir，sh 用 $APP_DIR。
// 这些常量作为 format! 的参数传入，其中的 `{`/`}` 是字面量。
// ---------------------------------------------------------------------------

const CMD_NODE_RESOLVE: &str = r#"
rem Prefer a version-compatible local node, fall back to the bundled runtime.
rem Pure batch version check (for /f tokens + numeric compare), no powershell
rem child: avoids console flashes when invoked without a console and skips the
rem per-call powershell startup cost.
where node >nul 2>nul
if errorlevel 1 goto :use_bundled
for /f "tokens=1,2 delims=v." %%a in ('node --version 2^>nul ^| findstr /b "v"') do set "NODE_MAJOR=%%a" & set "NODE_MINOR=%%b"
if not defined NODE_MAJOR goto :use_bundled
if %NODE_MAJOR% GEQ 24 goto :node_ok
if %NODE_MAJOR% EQU 22 if defined NODE_MINOR if %NODE_MINOR% GEQ 15 goto :node_ok
if %NODE_MAJOR% EQU 23 if defined NODE_MINOR if %NODE_MINOR% GEQ 8 goto :node_ok
goto :use_bundled

:node_ok
set "NODE=node"
goto :launch

:use_bundled
if not exist "%APP_DIR%\runtime\node.exe" goto :no_node
set "NODE=%APP_DIR%\runtime\node.exe"
set "PATH=%APP_DIR%\runtime;%PATH%"
"#;

const PS1_NODE_RESOLVE: &str = r#"
# Prefer a version-compatible local node, fall back to the bundled runtime.
$node = $null
$localNode = Get-Command node -ErrorAction SilentlyContinue
if ($localNode) {
    try {
        $version = & node --version 2>$null
        if ($version -match '^v(\d+)\.(\d+)') {
            $major = [int]$matches[1]
            $minor = [int]$matches[2]
            if (($major -eq 22 -and $minor -ge 15) -or ($major -eq 23 -and $minor -ge 8) -or $major -ge 24) {
                $node = 'node'
            }
        }
    } catch { }
}
if (-not $node) {
    $bundled = Join-Path $appDir 'runtime\node.exe'
    if (Test-Path -LiteralPath $bundled) {
        $node = $bundled
        $env:PATH = (Split-Path -Parent $bundled) + ';' + $env:PATH
    }
}
if (-not $node) {
    Write-Error 'Node.js runtime not found. Please run DeepSeek Harness Desktop to install it first.'
    exit 1
}
"#;

const SH_NODE_RESOLVE: &str = r#"
NODE=""
if command -v node >/dev/null 2>&1; then
  NODE_V=$(node --version 2>/dev/null)
  MAJOR=$(printf '%s' "$NODE_V" | awk -F. '{ gsub(/^v/, "", $1); print $1 }')
  MINOR=$(printf '%s' "$NODE_V" | awk -F. '{ print $2 }')
  if { [ -n "$MAJOR" ] && [ "$MAJOR" -ge 24 ]; } 2>/dev/null || \
     { [ "$MAJOR" -eq 22 ] && [ "$MINOR" -ge 15 ]; } 2>/dev/null || \
     { [ "$MAJOR" -eq 23 ] && [ "$MINOR" -ge 8 ]; } 2>/dev/null; then
    NODE="node"
  fi
fi
if [ -z "$NODE" ]; then
  if [ -x "$APP_DIR/runtime/bin/node" ]; then
    NODE="$APP_DIR/runtime/bin/node"
    export PATH="$APP_DIR/runtime/bin:$PATH"
  fi
fi
if [ -z "$NODE" ]; then
  echo "Node.js runtime not found. Please run DeepSeek Harness Desktop to install it first." >&2
  exit 1
fi
"#;

// ---------------------------------------------------------------------------
// 路径转义（按目标脚本语言的字符串规则）
// ---------------------------------------------------------------------------

/// 批处理中 `%` 会被展开，需写成 `%%`
#[inline]
pub fn escape_path_cmd(path: &Path) -> String {
    path.to_string_lossy().replace('%', "%%")
}

/// 单引号字符串中 `'` 需翻倍
#[inline]
pub fn escape_path_ps1(path: &Path) -> String {
    path.to_string_lossy().replace('\'', "''")
}

/// 单引号字符串中 `'` 需写成 `'\''`
#[inline]
pub fn escape_path_sh(path: &Path) -> String {
    path.to_string_lossy().replace('\'', "'\\''")
}

// ---------------------------------------------------------------------------
// dsh shim
// ---------------------------------------------------------------------------

/// Windows `dsh.cmd` 内容。`app_dir` 为应用数据目录（绝对路径，生成时写死）。
pub fn build_cmd_shim(app_dir: &Path) -> String {
    let dsh_bin = app_dir.join("dependencies/dsh/node_modules/@deepseek-ai/dsh/lib/bin.js");
    let dsh_home = app_dir.join("data/dsh");

    format!(
        r#"@echo off
rem DeepSeek Harness Desktop - dsh command shim (generated)
rem Do not edit: regenerated by the desktop app on install/startup.
setlocal
set "APP_DIR={app_dir}"
set "DSH_BIN={dsh_bin}"
set "DSH_HOME={dsh_home}"
set "DSH_TELEMETRY_DISABLED=1"
{node_resolve}
:launch
if not exist "%DSH_BIN%" goto :no_cli
"%NODE%" "%DSH_BIN%" %*
exit /b %ERRORLEVEL%

:no_cli
echo [dsh] Harness CLI not found. Please run DeepSeek Harness Desktop to install it first. 1>&2
exit /b 1

:no_node
echo [dsh] Node.js runtime not found. Please run DeepSeek Harness Desktop to install it first. 1>&2
exit /b 1
"#,
        app_dir = escape_path_cmd(app_dir),
        dsh_bin = escape_path_cmd(&dsh_bin),
        dsh_home = escape_path_cmd(&dsh_home),
        node_resolve = CMD_NODE_RESOLVE,
    )
}

/// Windows `dsh.ps1` 内容
pub fn build_ps1_shim(app_dir: &Path) -> String {
    let dsh_bin = app_dir.join("dependencies/dsh/node_modules/@deepseek-ai/dsh/lib/bin.js");
    let dsh_home = app_dir.join("data/dsh");

    format!(
        r#"# DeepSeek Harness Desktop - dsh command shim (generated)
# Do not edit: regenerated by the desktop app on install/startup.
$ErrorActionPreference = "Stop"
$appDir = '{app_dir}'
$dshBin = '{dsh_bin}'
$env:DSH_HOME = '{dsh_home}'
$env:DSH_TELEMETRY_DISABLED = '1'
{node_resolve}
if (-not (Test-Path -LiteralPath $dshBin)) {{
    Write-Error '[dsh] Harness CLI not found. Please run DeepSeek Harness Desktop to install it first.'
    exit 1
}}
& $node $dshBin @args
exit $LASTEXITCODE
"#,
        app_dir = escape_path_ps1(app_dir),
        dsh_bin = escape_path_ps1(&dsh_bin),
        dsh_home = escape_path_ps1(&dsh_home),
        node_resolve = PS1_NODE_RESOLVE,
    )
}

/// Unix `dsh` shell 脚本内容（POSIX sh）
#[cfg(not(windows))]
pub fn build_sh_shim(app_dir: &Path) -> String {
    let dsh_bin = app_dir.join("dependencies/dsh/node_modules/@deepseek-ai/dsh/lib/bin.js");
    let dsh_home = app_dir.join("data/dsh");

    format!(
        r#"#!/bin/sh
# DeepSeek Harness Desktop - dsh command shim (generated)
# Do not edit: regenerated by the desktop app on install/startup.
APP_DIR='{app_dir}'
DSH_BIN='{dsh_bin}'
export DSH_HOME='{dsh_home}'
export DSH_TELEMETRY_DISABLED=1
{node_resolve}
if [ ! -f "$DSH_BIN" ]; then
  echo "[dsh] Harness CLI not found. Please run DeepSeek Harness Desktop to install it first." >&2
  exit 1
fi
exec "$NODE" "$DSH_BIN" "$@"
"#,
        app_dir = escape_path_sh(app_dir),
        dsh_bin = escape_path_sh(&dsh_bin),
        dsh_home = escape_path_sh(&dsh_home),
        node_resolve = SH_NODE_RESOLVE,
    )
}

// ---------------------------------------------------------------------------
// pnpm shim（额外带"用户 pnpm 优先"逻辑，见各函数注释）
// ---------------------------------------------------------------------------

/// Windows `pnpm.cmd` 内容：优先转发用户自己安装的 pnpm（`where pnpm` 遍历、
/// 跳过本 shim 目录、只收 `.cmd/.exe/.bat`），否则用 node 运行捆绑 pnpm.cjs。
///
/// 实现要点：
/// - 不用 `findstr` 匹配路径（`\` 会被当正则转义导致过滤失效）；
/// - 块内变量判断用 for 变量（`%%~xp`）而非 `%VAR%`（块解析时机陷阱）。
pub fn build_pnpm_cmd_shim(app_dir: &Path) -> String {
    let pnpm_bin = app_dir.join("dependencies/pnpm/bin/pnpm.cjs");

    format!(
        r#"@echo off
rem DeepSeek Harness Desktop - pnpm command shim (generated)
rem Do not edit: regenerated by the desktop app on install/startup.
setlocal
set "APP_DIR={app_dir}"
set "PNPM_BIN={pnpm_bin}"

rem Prefer a user-installed pnpm (skip our own shim dir), fall back to bundled.
rem Accept only executable extensions (.cmd/.exe/.bat), ignore extensionless shell scripts.
set "SELF_PREFIX=%~dp0"
set "SELF_PREFIX=%SELF_PREFIX:~0,-1%"
set "USER_PNPM="
for /f "delims=" %%p in ('where pnpm 2^>nul') do (
  if not defined USER_PNPM (
    if /i not "%%p"=="%SELF_PREFIX%\pnpm.cmd" (
      if /i not "%%p"=="%SELF_PREFIX%\pnpm.exe" (
        if /i not "%%p"=="%SELF_PREFIX%\pnpm.bat" (
          if /i "%%~xp"==".cmd" set "USER_PNPM=%%p"
          if /i "%%~xp"==".exe" set "USER_PNPM=%%p"
          if /i "%%~xp"==".bat" set "USER_PNPM=%%p"
        )
      )
    )
  )
)
if defined USER_PNPM (
  call "%USER_PNPM%" %*
  exit /b %ERRORLEVEL%
)
{node_resolve}
:launch
if not exist "%PNPM_BIN%" goto :no_pnpm
"%NODE%" "%PNPM_BIN%" %*
exit /b %ERRORLEVEL%

:no_pnpm
echo [pnpm] pnpm not found. Please run DeepSeek Harness Desktop to install it first. 1>&2
exit /b 1

:no_node
echo [pnpm] Node.js runtime not found. Please run DeepSeek Harness Desktop to install it first. 1>&2
exit /b 1
"#,
        app_dir = escape_path_cmd(app_dir),
        pnpm_bin = escape_path_cmd(&pnpm_bin),
        node_resolve = CMD_NODE_RESOLVE,
    )
}

/// Windows `pnpm.ps1` 内容：优先转发用户 pnpm（`Get-Command pnpm -All`，
/// 排除本 shim 目录），否则用 node 运行捆绑 pnpm.cjs。
pub fn build_pnpm_ps1_shim(app_dir: &Path) -> String {
    let pnpm_bin = app_dir.join("dependencies/pnpm/bin/pnpm.cjs");

    format!(
        r#"# DeepSeek Harness Desktop - pnpm command shim (generated)
# Do not edit: regenerated by the desktop app on install/startup.
$ErrorActionPreference = "Stop"
$appDir = '{app_dir}'
$pnpmBin = '{pnpm_bin}'

# Prefer a user-installed pnpm (skip our own shim dir), fall back to bundled.
$selfDir = $PSScriptRoot.TrimEnd('\') + '\'
$userPnpm = Get-Command pnpm -All -ErrorAction SilentlyContinue |
    Where-Object {{ $_.Source -and -not $_.Source.StartsWith($selfDir, [System.StringComparison]::OrdinalIgnoreCase) }} |
    Select-Object -First 1
if ($userPnpm) {{
    & $userPnpm.Source @args
    exit $LASTEXITCODE
}}
{node_resolve}
if (-not (Test-Path -LiteralPath $pnpmBin)) {{
    Write-Error '[pnpm] pnpm not found. Please run DeepSeek Harness Desktop to install it first.'
    exit 1
}}
& $node $pnpmBin @args
exit $LASTEXITCODE
"#,
        app_dir = escape_path_ps1(app_dir),
        pnpm_bin = escape_path_ps1(&pnpm_bin),
        node_resolve = PS1_NODE_RESOLVE,
    )
}

/// Unix `pnpm` shell 脚本内容（POSIX sh）：按 PATH 顺序转发第一个非本目录
/// 的用户 pnpm，否则用 node 运行捆绑 pnpm.cjs。
#[cfg_attr(all(windows, not(test)), allow(dead_code))]
pub fn build_pnpm_sh_shim(app_dir: &Path) -> String {
    let pnpm_bin = app_dir.join("dependencies/pnpm/bin/pnpm.cjs");

    format!(
        r#"#!/bin/sh
# DeepSeek Harness Desktop - pnpm command shim (generated)
# Do not edit: regenerated by the desktop app on install/startup.
APP_DIR='{app_dir}'
PNPM_BIN='{pnpm_bin}'

# Prefer a user-installed pnpm (skip our own shim dir), fall back to bundled.
SELF_DIR=$(cd "$(dirname "$0")" && pwd)
IFS=:
for dir in $PATH; do
  if [ "$dir" = "$SELF_DIR" ]; then
    continue
  fi
  if [ -x "$dir/pnpm" ]; then
    exec "$dir/pnpm" "$@"
  fi
done
unset IFS
{node_resolve}
if [ ! -f "$PNPM_BIN" ]; then
  echo "[pnpm] pnpm not found. Please run DeepSeek Harness Desktop to install it first." >&2
  exit 1
fi
exec "$NODE" "$PNPM_BIN" "$@"
"#,
        app_dir = escape_path_sh(app_dir),
        pnpm_bin = escape_path_sh(&pnpm_bin),
        node_resolve = SH_NODE_RESOLVE,
    )
}

// ---------------------------------------------------------------------------
// 落盘
// ---------------------------------------------------------------------------

/// 将 shim 文件写入 bin 目录（覆盖式，保证自愈后内容与当前安装一致）
pub fn write_shims(app_handle: &AppHandle, bin_dir: &Path) -> Result<(), String> {
    let app_dir = config::get_base_dir(app_handle);
    fs::create_dir_all(bin_dir).map_err(|e| format!("create bin dir failed: {e}"))?;

    #[cfg(windows)]
    {
        fs::write(bin_dir.join(SHIM_CMD_NAME), build_cmd_shim(&app_dir))
            .map_err(|e| format!("write {SHIM_CMD_NAME} failed: {e}"))?;
        fs::write(bin_dir.join(SHIM_PS1_NAME), build_ps1_shim(&app_dir))
            .map_err(|e| format!("write {SHIM_PS1_NAME} failed: {e}"))?;
        fs::write(bin_dir.join(PNPM_SHIM_CMD_NAME), build_pnpm_cmd_shim(&app_dir))
            .map_err(|e| format!("write {PNPM_SHIM_CMD_NAME} failed: {e}"))?;
        fs::write(bin_dir.join(PNPM_SHIM_PS1_NAME), build_pnpm_ps1_shim(&app_dir))
            .map_err(|e| format!("write {PNPM_SHIM_PS1_NAME} failed: {e}"))?;
    }
    #[cfg(not(windows))]
    {
        // 类型由右侧推断，避免 Windows 构建引入未使用的 PathBuf 导入
        let shims = [
            (bin_dir.join(SHIM_SH_NAME), build_sh_shim(&app_dir)),
            (bin_dir.join(PNPM_SHIM_SH_NAME), build_pnpm_sh_shim(&app_dir)),
        ];
        for (shim, content) in shims {
            fs::write(&shim, content)
                .map_err(|e| format!("write {} failed: {e}", shim.display()))?;
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                fs::set_permissions(&shim, fs::Permissions::from_mode(0o755))
                    .map_err(|e| format!("chmod shim failed: {e}"))?;
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn sample_app_dir() -> PathBuf {
        if cfg!(windows) {
            PathBuf::from(r"C:\Users\test\AppData\Roaming\io.github.hairyf.deepseek-harness-desktop")
        } else {
            PathBuf::from("/home/test/.local/share/io.github.hairyf.deepseek-harness-desktop")
        }
    }

    #[test]
    fn cmd_shim_contains_baked_paths() {
        let content = build_cmd_shim(&sample_app_dir());
        assert!(content.contains(r"C:\Users\test\AppData\Roaming"));
        assert!(content.contains("dependencies/dsh/node_modules/@deepseek-ai/dsh/lib/bin.js"));
        assert!(content.contains("data/dsh"));
        assert!(content.contains("%*"));
    }

    #[test]
    fn cmd_shim_escapes_percent() {
        let dir = PathBuf::from(r"C:\Users\100%test\AppData\Roaming\io.github.hairyf.deepseek-harness-desktop");
        let content = build_cmd_shim(&dir);
        assert!(content.contains("100%%test"));
        assert!(!content.contains(r#"set "APP_DIR=C:\Users\100%test""#));
    }

    #[test]
    fn pnpm_cmd_shim_contains_user_precedence() {
        let content = build_pnpm_cmd_shim(&sample_app_dir());
        assert!(content.contains("pnpm command shim"));
        assert!(content.contains(r#"dependencies/pnpm/bin/pnpm.cjs"#));
        assert!(content.contains("where pnpm"));
        assert!(content.contains("SELF_PREFIX"));
        assert!(content.contains(r#"call "%USER_PNPM%" %*"#));
        assert!(content.contains(":use_bundled"));
        assert!(content.contains("%APP_DIR%\\runtime\\node.exe"));
    }

    #[test]
    fn pnpm_ps1_shim_contains_user_precedence() {
        let content = build_pnpm_ps1_shim(&sample_app_dir());
        assert!(content.contains("Get-Command pnpm -All"));
        assert!(content.contains("$PSScriptRoot"));
        assert!(content.contains("$userPnpm.Source"));
        assert!(content.contains("@args"));
        assert!(content.contains("Join-Path $appDir 'runtime\\node.exe'"));
    }

    #[test]
    fn pnpm_sh_shim_contains_user_precedence() {
        let content = build_pnpm_sh_shim(&sample_app_dir());
        assert!(content.starts_with("#!/bin/sh"));
        assert!(content.contains(r#"exec "$dir/pnpm" "$@""#));
        assert!(content.contains("SELF_DIR"));
        assert!(content.contains(r#"exec "$NODE" "$PNPM_BIN" "$@""#));
        assert!(content.contains(r#"$APP_DIR/runtime/bin/node"#));
    }

    #[test]
    fn ps1_shim_escapes_quotes() {
        let dir = PathBuf::from(r"C:\Users\o'brien\AppData\Roaming\io.github.hairyf.deepseek-harness-desktop");
        let content = build_ps1_shim(&dir);
        assert!(content.contains(r"o''brien"));
    }
}
